[project]
name = "reboot-random-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
required-environments = [
    "sys_platform == 'win32' or sys_platform == 'win_amd64' or sys_platform == 'win_arm64'"
]